# Generated by Django 4.1.7 on 2023-05-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbetapp', '0002_game_member_email_member_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
