# Generated by Django 4.1.7 on 2023-06-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbetapp', '0016_alter_market_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=125)),
                ('firstname', models.CharField(max_length=125)),
                ('lastname', models.CharField(max_length=125)),
                ('phone', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='market',
            name='bookmaker',
        ),
        migrations.RemoveField(
            model_name='market',
            name='game',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='market',
        ),
        migrations.RemoveField(
            model_name='game',
            name='sport_key',
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Bookmaker',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
    ]
