# Generated by Django 4.1.7 on 2023-06-02 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbetapp', '0020_bookmaker_game_bookmakers'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('point', models.FloatField(blank=True, null=True)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='sportsbetapp.bookmaker')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='sportsbetapp.game')),
            ],
        ),
    ]
