# Generated by Django 4.1.7 on 2023-06-01 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbetapp', '0004_rename_start_time_game_commence_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField()),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='sportsbetapp.bookmaker')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='sport_key',
            field=models.CharField(default='temp_default', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='sport_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='sportsbetapp.market')),
            ],
        ),
        migrations.AddField(
            model_name='bookmaker',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmakers', to='sportsbetapp.game'),
        ),
    ]
