# Generated by Django 4.1.7 on 2023-06-01 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbetapp', '0005_bookmaker_market_game_sport_key_game_sport_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmaker',
            name='game',
        ),
        migrations.RemoveField(
            model_name='game',
            name='sport_title',
        ),
        migrations.RemoveField(
            model_name='market',
            name='last_update',
        ),
        migrations.AddField(
            model_name='market',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='sportsbetapp.game'),
        ),
    ]
