# Generated by Django 4.1.7 on 2023-06-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbetapp', '0019_alter_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='bookmakers',
            field=models.ManyToManyField(related_name='games', to='sportsbetapp.bookmaker'),
        ),
    ]
