# Generated by Django 4.1.7 on 2023-06-02 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbetapp', '0021_gameoutcome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameOutcome',
            new_name='Outcome',
        ),
        migrations.RemoveField(
            model_name='game',
            name='bookmakers',
        ),
        migrations.AddField(
            model_name='bookmaker',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmakers', to='sportsbetapp.game'),
        ),
    ]
