# Generated by Django 4.1.7 on 2023-06-02 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbetapp', '0023_remove_outcome_bookmaker_remove_outcome_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('point', models.FloatField(blank=True, null=True)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsbetapp.bookmaker')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsbetapp.game')),
            ],
        ),
    ]
