# Generated by Django 4.1.7 on 2023-06-02 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbetapp', '0024_bookmaker_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='bookmaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='sportsbetapp.bookmaker'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='sportsbetapp.game'),
        ),
    ]
