# Generated by Django 4.1.7 on 2023-06-15 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbetapp', '0025_alter_outcome_bookmaker_alter_outcome_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField()),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='sportsbetapp.bookmaker')),
            ],
        ),
    ]
