# Generated by Django 4.1.7 on 2023-06-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbetapp', '0027_game_outcomes_game_sport_key_game_sport_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='outcomes',
            field=models.JSONField(null=True),
        ),
    ]
