# Generated by Django 4.1.7 on 2023-07-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbetapp', '0028_alter_game_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmaker',
            name='key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
