# Generated by Django 4.1.7 on 2023-08-22 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbetapp', '0031_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='sport_key',
        ),
        migrations.RemoveField(
            model_name='game',
            name='sport_title',
        ),
        migrations.AddField(
            model_name='game',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='sportsbetapp.sport'),
        ),
    ]
